config/routes.rb
Rails.application.routes.draw do
  resources :anesthesia_types
  resources :backups do
    member do
      get 'restore'
    end
  end
  resources :admission_statuses
  resources :beds
  resources :occupation_groups
  resources :regions
  resources :or_blocks
  resources :procedure_categories
  get 'report/backlog'
  get 'report/waitlist'
  get 'report/surgical_service'
  get 'report/surgical_service_efficiency'
  get 'report/surgical_efficiency'
  get 'report/load_surgical_service'
  get 'report/load_surgical_service_efficiency'
  get 'report/custom_report'
  get 'report/load_admissions'
  resources :surgical_services do
    collection do
      get 'surgeries_by_status_by_month'
      get 'surgical_service_efficiency_by_month'
      get 'average_procedure_duration_by_month'
      get 'load_sub_form'
      get 'load_death_reason'
      get 'load_adverse_event'
    end
  end
  resources :or_schedules do
    collection do
      get 'load_patients'
      get 'load_sub_form'
      get 'today'
      get 'load_or_tables'
    end
  end
  resources :phone_calls do
    collection do
      get 'load_sub_form'
      get 'load_appointment_date'
    end
  end
  resources :admissions do
    collection do
      get 'load_beds'
    end
    member do
      get 'admission'
    end
    collection do
      get 'patients_by_status_by_month'
      get 'load_sub_form'
      get 'load_information'
      get 'load_category'
      get 'load_priority'
      get 'load_submit'
    end
  end
  resources :patients do
    collection do
      get 'appointment_list'
      get 'load_appointments'
      get 'admitted_list'
      get 'shortlist'
      get 'load_age'
      get 'load_age_or_dob'
      get 'load_patients'
      post 'create_from_search'
    end
  end
  resources :anesthesians
  resources :circulating_nurses
  resources :scrub_nurses
  resources :surgeons
  resources :departments
  resources :physicians
  resources :or_tables
  resources :payment_types
  resources :procedures do
    collection do
      post 'import'
    end
  end
  resources :diagnoses do
    collection do
      post 'import'
    end
  end
  resources :wards
  resources :hospitals
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
  }
  scope "/admin" do
    resources :users
  end
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/surgeon.rb
class Surgeon < ApplicationRecord
  default_scope -> {where(status: true)}

  belongs_to :hospital
  belongs_to :occupation_group

  validates :name, presence: true

  def surgeon_status
    status == true ? 'Active' : 'Disabled'
  end

  def to_s
    name
  end
end

app/controllers/surgeons_controller.rb
class SurgeonsController < ApplicationController
  before_action :set_surgeon, only: [:show, :edit, :update, :destroy]

  # GET /surgeons
  # GET /surgeons.json
  def index
    @surgeons = Surgeon.unscoped.all
  end

  # GET /surgeons/1
  # GET /surgeons/1.json
  def show
  end

  # GET /surgeons/new
  def new
    @surgeon = Surgeon.new
    @surgeon.hospital_id = current_user.hospital_id
  end

  # GET /surgeons/1/edit
  def edit
  end

  # POST /surgeons
  # POST /surgeons.json
  def create
    @surgeon = Surgeon.new(surgeon_params)

    respond_to do |format|
      if @surgeon.save
        format.html { redirect_to surgeons_path, notice: 'Surgeon was successfully created.' }
        format.json { render :show, status: :created, location: @surgeon }
      else
        format.html { render :new }
        format.json { render json: @surgeon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surgeons/1
  # PATCH/PUT /surgeons/1.json
  def update
    respond_to do |format|
      if @surgeon.update(surgeon_params)
        format.html { redirect_to surgeons_path, notice: 'Surgeon was successfully updated.' }
        format.json { render :show, status: :ok, location: @surgeon }
      else
        format.html { render :edit }
        format.json { render json: @surgeon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surgeons/1
  # DELETE /surgeons/1.json
  def destroy
    @surgeon.destroy
    respond_to do |format|
      format.html { redirect_to surgeons_url, notice: 'Surgeon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_surgeon
      @surgeon = Surgeon.unscoped.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def surgeon_params
      params.require(:surgeon).permit(:name, :occupation_group_id, :hospital_id, :status)
    end
end

app/helpers/surgeons_helper.rb
module SurgeonsHelper
end

app/views/surgeons/_form.html.erb
<%= simple_form_for(@surgeon) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :occupation_group %>
    <%= f.association :hospital, as: :hidden %>
    <div class="offset-3">
    <%= f.input :status, wrapper: :vertical_boolean, as: :boolean, label: "Active" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/surgeons/edit.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: { title: "Edit Surgeon" } %>

app/views/surgeons/index.html.erb
<div class="card shadow mb-4">
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Surgeons</h6>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <table class="table table-bordered dataTable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Occupation Group</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @surgeons.each do |surgeon| %>
      <tr>
        <td><%= surgeon.name %></td>
        <td><%= surgeon.occupation_group %></td>
        <td><%= surgeon.surgeon_status %></td>
        <td><%= link_to 'Edit', edit_surgeon_path(surgeon) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Surgeon', new_surgeon_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/surgeons/new.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: { title: "New Surgeon" } %>

app/views/surgeons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @surgeon.name %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @surgeon.hospital %>
</p>

<%= link_to 'Edit', edit_surgeon_path(@surgeon) %> |
<%= link_to 'Back', surgeons_path %>