config/routes.rb
Rails.application.routes.draw do
  resources :anesthesia_types
  resources :backups do
    member do
      get 'restore'
    end
  end
  resources :admission_statuses
  resources :beds
  resources :occupation_groups
  resources :regions
  resources :or_blocks
  resources :procedure_categories
  get 'report/backlog'
  get 'report/waitlist'
  get 'report/surgical_service'
  get 'report/surgical_service_efficiency'
  get 'report/surgical_efficiency'
  get 'report/load_surgical_service'
  get 'report/load_surgical_service_efficiency'
  get 'report/custom_report'
  get 'report/load_admissions'
  resources :surgical_services do
    collection do
      get 'surgeries_by_status_by_month'
      get 'surgical_service_efficiency_by_month'
      get 'average_procedure_duration_by_month'
      get 'load_sub_form'
      get 'load_death_reason'
      get 'load_adverse_event'
    end
  end
  resources :or_schedules do
    collection do
      get 'load_patients'
      get 'load_sub_form'
      get 'today'
      get 'load_or_tables'
    end
  end
  resources :phone_calls do
    collection do
      get 'load_sub_form'
      get 'load_appointment_date'
    end
  end
  resources :admissions do
    collection do
      get 'load_beds'
    end
    member do
      get 'admission'
    end
    collection do
      get 'patients_by_status_by_month'
      get 'load_sub_form'
      get 'load_information'
      get 'load_category'
      get 'load_priority'
      get 'load_submit'
    end
  end
  resources :patients do
    collection do
      get 'appointment_list'
      get 'load_appointments'
      get 'admitted_list'
      get 'shortlist'
      get 'load_age'
      get 'load_age_or_dob'
      get 'load_patients'
      post 'create_from_search'
    end
  end
  resources :anesthesians
  resources :circulating_nurses
  resources :scrub_nurses
  resources :surgeons
  resources :departments
  resources :physicians
  resources :or_tables
  resources :payment_types
  resources :procedures do
    collection do
      post 'import'
    end
  end
  resources :diagnoses do
    collection do
      post 'import'
    end
  end
  resources :wards
  resources :hospitals
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
  }
  scope "/admin" do
    resources :users
  end
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/occupation_group.rb
class OccupationGroup < ApplicationRecord

  validates :name, presence: true

  def to_s
    name
  end
end

app/controllers/occupation_groups_controller.rb
class OccupationGroupsController < ApplicationController
  before_action :set_occupation_group, only: [:show, :edit, :update, :destroy]

  # GET /occupation_groups
  # GET /occupation_groups.json
  def index
    @occupation_groups = OccupationGroup.all
  end

  # GET /occupation_groups/1
  # GET /occupation_groups/1.json
  def show
  end

  # GET /occupation_groups/new
  def new
    @occupation_group = OccupationGroup.new
  end

  # GET /occupation_groups/1/edit
  def edit
  end

  # POST /occupation_groups
  # POST /occupation_groups.json
  def create
    @occupation_group = OccupationGroup.new(occupation_group_params)

    respond_to do |format|
      if @occupation_group.save
        format.html { redirect_to occupation_groups_path, notice: 'Occupation group was successfully created.' }
        format.json { render :show, status: :created, location: @occupation_group }
      else
        format.html { render :new }
        format.json { render json: @occupation_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /occupation_groups/1
  # PATCH/PUT /occupation_groups/1.json
  def update
    respond_to do |format|
      if @occupation_group.update(occupation_group_params)
        format.html { redirect_to occupation_groups_path, notice: 'Occupation group was successfully updated.' }
        format.json { render :show, status: :ok, location: @occupation_group }
      else
        format.html { render :edit }
        format.json { render json: @occupation_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occupation_groups/1
  # DELETE /occupation_groups/1.json
  def destroy
    @occupation_group.destroy
    respond_to do |format|
      format.html { redirect_to occupation_groups_url, notice: 'Occupation group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_occupation_group
      @occupation_group = OccupationGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def occupation_group_params
      params.require(:occupation_group).permit(:name)
    end
end

app/helpers/occupation_groups_helper.rb
module OccupationGroupsHelper
end

app/views/occupation_groups/_form.html.erb
<%= simple_form_for(@occupation_group) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/occupation_groups/edit.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: {title: "Edit Occupation Group" } %>

app/views/occupation_groups/index.html.erb
<div class="card shadow mb-4">
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Occupation Groups</h6>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <table class="table table-bordered dataTable">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @occupation_groups.each do |occupation_group| %>
      <tr>
        <td><%= occupation_group.name %></td>
        <td><%= link_to 'Edit', edit_occupation_group_path(occupation_group) %> |
          <%= link_to 'Delete', occupation_group, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Occupation Group', new_occupation_group_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/occupation_groups/new.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: {title: "Add Occupation Group" } %>

app/views/occupation_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @occupation_group.name %>
</p>

<%= link_to 'Edit', edit_occupation_group_path(@occupation_group) %> |
<%= link_to 'Back', occupation_groups_path %>