config/routes.rb
Rails.application.routes.draw do
  resources :anesthesia_types
  resources :backups do
    member do
      get 'restore'
    end
  end
  resources :admission_statuses
  resources :beds
  resources :occupation_groups
  resources :regions
  resources :or_blocks
  resources :procedure_categories
  get 'report/backlog'
  get 'report/waitlist'
  get 'report/surgical_service'
  get 'report/surgical_service_efficiency'
  get 'report/surgical_efficiency'
  get 'report/load_surgical_service'
  get 'report/load_surgical_service_efficiency'
  get 'report/custom_report'
  get 'report/load_admissions'
  resources :surgical_services do
    collection do
      get 'surgeries_by_status_by_month'
      get 'surgical_service_efficiency_by_month'
      get 'average_procedure_duration_by_month'
      get 'load_sub_form'
      get 'load_death_reason'
      get 'load_adverse_event'
    end
  end
  resources :or_schedules do
    collection do
      get 'load_patients'
      get 'load_sub_form'
      get 'today'
      get 'load_or_tables'
    end
  end
  resources :phone_calls do
    collection do
      get 'load_sub_form'
      get 'load_appointment_date'
    end
  end
  resources :admissions do
    collection do
      get 'load_beds'
    end
    member do
      get 'admission'
    end
    collection do
      get 'patients_by_status_by_month'
      get 'load_sub_form'
      get 'load_information'
      get 'load_category'
      get 'load_priority'
      get 'load_submit'
    end
  end
  resources :patients do
    collection do
      get 'appointment_list'
      get 'load_appointments'
      get 'admitted_list'
      get 'shortlist'
      get 'load_age'
      get 'load_age_or_dob'
      get 'load_patients'
      post 'create_from_search'
    end
  end
  resources :anesthesians
  resources :circulating_nurses
  resources :scrub_nurses
  resources :surgeons
  resources :departments
  resources :physicians
  resources :or_tables
  resources :payment_types
  resources :procedures do
    collection do
      post 'import'
    end
  end
  resources :diagnoses do
    collection do
      post 'import'
    end
  end
  resources :wards
  resources :hospitals
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
  }
  scope "/admin" do
    resources :users
  end
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :procedure_category
  has_many :admissions

  validates :name, presence: true

  def self.import(file)
    procedures = []
    CSV.foreach(file.path, :headers=>true, encoding: 'iso-8859-1:utf-8') do |row|
      name = row[0]
      category = row[1].blank? ? nil : ProcedureCategory.find_or_create_by(code: row[1].strip)
      attrbts = {name: name, procedure_category_id: category.try(:id)}
      p = Procedure.find_or_create_by(attrbts)
      unless p.blank?
        procedures << p unless p.blank?
      end
    end
    return procedures
  end

  def to_s
    name
  end

end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :set_procedure, only: [:show, :edit, :update, :destroy]

  # GET /procedures
  # GET /procedures.json
  def index
    @procedures = Procedure.all
  end

  def import
    if request.post?
      @procedures = Procedure.import(params[:procedures_csv_file])
      flash[:notice] = @procedures.blank? ? 'No procedure imported' : 'Procedures imported'
    end
    redirect_to procedures_path
  end

  # GET /procedures/1
  # GET /procedures/1.json
  def show
  end

  # GET /procedures/new
  def new
    @procedure = Procedure.new
  end

  # GET /procedures/1/edit
  def edit
  end

  # POST /procedures
  # POST /procedures.json
  def create
    @procedure = Procedure.new(procedure_params)

    respond_to do |format|
      if @procedure.save
        format.html { redirect_to procedures_path, notice: 'Procedure was successfully created.' }
        format.json { render :show, status: :created, location: @procedure }
      else
        format.html { render :new }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /procedures/1
  # PATCH/PUT /procedures/1.json
  def update
    respond_to do |format|
      if @procedure.update(procedure_params)
        format.html { redirect_to procedures_path, notice: 'Procedure was successfully updated.' }
        format.json { render :show, status: :ok, location: @procedure }
      else
        format.html { render :edit }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /procedures/1
  # DELETE /procedures/1.json
  def destroy
    @procedure.destroy
    respond_to do |format|
      format.html { redirect_to procedures_url, notice: 'Procedure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_procedure
      @procedure = Procedure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def procedure_params
      params.require(:procedure).permit(:name, :procedure_category_id)
    end
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form.html.erb
<%= simple_form_for(@procedure) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :procedure_category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/procedures/edit.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: { title: "Edit Procedure" } %>

app/views/procedures/index.html.erb
<div class="card shadow mb-4">
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Procedures</h6>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <table class="table table-bordered dataTable" width="100%" cellspacing="0">
  <thead>
    <tr>
      <th>Name</th>
      <th>Procedure Category</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @procedures.each do |procedure| %>
      <tr>
        <td><%= procedure.name %></td>
        <td><%= procedure.procedure_category %></td>
        <td><%= link_to 'Edit', edit_procedure_path(procedure) %> |
          <%= link_to 'Delete', procedure, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Procedure', new_procedure_path, class: 'btn btn-primary' %>
<hr/>
  <%= form_tag import_procedures_path,:multipart=>true do %>
      <div class="row">
      <div class="col-sm-3">
        <label>Select CSV File</label> <%= file_field_tag(:procedures_csv_file) %>
      </div>
      <div class="col-sm-3">
        <%= submit_tag 'Import',class: 'btn btn-primary' %>
      </div>
      </div>
  <% end %>
  </div>
</div>

app/views/procedures/new.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: { title: "New Procedure" } %>

app/views/procedures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @procedure.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @procedure.category %>
</p>

<p>
  <strong>Max appointment days:</strong>
  <%= @procedure.max_appointment_days %>
</p>

<p>
  <strong>Max postponment days:</strong>
  <%= @procedure.max_postponment_days %>
</p>

<%= link_to 'Edit', edit_procedure_path(@procedure) %> |
<%= link_to 'Back', procedures_path %>