config/routes.rb
Rails.application.routes.draw do
  resources :anesthesia_types
  resources :backups do
    member do
      get 'restore'
    end
  end
  resources :admission_statuses
  resources :beds
  resources :occupation_groups
  resources :regions
  resources :or_blocks
  resources :procedure_categories
  get 'report/backlog'
  get 'report/waitlist'
  get 'report/surgical_service'
  get 'report/surgical_service_efficiency'
  get 'report/surgical_efficiency'
  get 'report/load_surgical_service'
  get 'report/load_surgical_service_efficiency'
  get 'report/custom_report'
  get 'report/load_admissions'
  resources :surgical_services do
    collection do
      get 'surgeries_by_status_by_month'
      get 'surgical_service_efficiency_by_month'
      get 'average_procedure_duration_by_month'
      get 'load_sub_form'
      get 'load_death_reason'
      get 'load_adverse_event'
    end
  end
  resources :or_schedules do
    collection do
      get 'load_patients'
      get 'load_sub_form'
      get 'today'
      get 'load_or_tables'
    end
  end
  resources :phone_calls do
    collection do
      get 'load_sub_form'
      get 'load_appointment_date'
    end
  end
  resources :admissions do
    collection do
      get 'load_beds'
    end
    member do
      get 'admission'
    end
    collection do
      get 'patients_by_status_by_month'
      get 'load_sub_form'
      get 'load_information'
      get 'load_category'
      get 'load_priority'
      get 'load_submit'
    end
  end
  resources :patients do
    collection do
      get 'appointment_list'
      get 'load_appointments'
      get 'admitted_list'
      get 'shortlist'
      get 'load_age'
      get 'load_age_or_dob'
      get 'load_patients'
      post 'create_from_search'
    end
  end
  resources :anesthesians
  resources :circulating_nurses
  resources :scrub_nurses
  resources :surgeons
  resources :departments
  resources :physicians
  resources :or_tables
  resources :payment_types
  resources :procedures do
    collection do
      post 'import'
    end
  end
  resources :diagnoses do
    collection do
      post 'import'
    end
  end
  resources :wards
  resources :hospitals
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
  }
  scope "/admin" do
    resources :users
  end
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ward.rb
class Ward < ApplicationRecord
  belongs_to :hospital
  has_many :beds

  validates :name, presence: true

  def to_s
    name
  end

end

app/controllers/wards_controller.rb
class WardsController < ApplicationController
  before_action :set_ward, only: [:show, :edit, :update, :destroy]

  # GET /wards
  # GET /wards.json
  def index
    @wards = Ward.all
  end

  # GET /wards/1
  # GET /wards/1.json
  def show
  end

  # GET /wards/new
  def new
    @ward = Ward.new
    @ward.hospital_id = current_user.hospital_id
  end

  # GET /wards/1/edit
  def edit
  end

  # POST /wards
  # POST /wards.json
  def create
    @ward = Ward.new(ward_params)

    respond_to do |format|
      if @ward.save
        format.html { redirect_to wards_path, notice: 'Ward was successfully created.' }
        format.json { render :show, status: :created, location: @ward }
      else
        format.html { render :new }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wards/1
  # PATCH/PUT /wards/1.json
  def update
    respond_to do |format|
      if @ward.update(ward_params)
        format.html { redirect_to wards_path, notice: 'Ward was successfully updated.' }
        format.json { render :show, status: :ok, location: @ward }
      else
        format.html { render :edit }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wards/1
  # DELETE /wards/1.json
  def destroy
    @ward.destroy
    respond_to do |format|
      format.html { redirect_to wards_url, notice: 'Ward was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ward
      @ward = Ward.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ward_params
      params.require(:ward).permit(:name, :hospital_id)
    end
end

app/helpers/wards_helper.rb
module WardsHelper
end

app/views/wards/_form.html.erb
<%= simple_form_for(@ward) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :hospital, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/wards/edit.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: { title: "New Ward" } %>

app/views/wards/index.html.erb
<div class="card shadow mb-4">
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Wards</h6>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <table class="table table-bordered dataTable" width="100%" cellspacing="0">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @wards.each do |ward| %>
      <tr>
        <td><%= ward.name %></td>
        <td>
          <%= link_to 'Edit', edit_ward_path(ward) %> |
          <%= link_to 'Remove', ward, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Ward', new_ward_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/wards/new.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: { title: "Edit Ward" } %>

app/views/wards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ward.name %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @ward.hospital %>
</p>

<%= link_to 'Edit', edit_ward_path(@ward) %> |
<%= link_to 'Back', wards_path %>